config/routes.rb
Scenario::Application.routes.draw do

  match 'reports' => 'reports#index', :as => :reports
  match 'reports/show' => 'reports#show', :as => :show_reports

  match 'search' => 'search#index', :as => :search

  root :to => 'disciplines#index'

  resources :examines do
    collection { post :sort }
  end

  resources :blocks do
    member do
      post :add_groups
      post :add_examines
    end
    collection { get :year }
  end

  resources :repository_themes do
    collection {get :discipline_themes}
  end

  resources :scripts do
    resources :script_themes do
      resources :script_sub_themes
    end
  end

  resources :disciplines

  resources :groups

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

end

app/models/discipline.rb
class Discipline < ActiveRecord::Base
  has_and_belongs_to_many :repository_themes
  has_many :blocks
  
  validates_presence_of :name
  validates_uniqueness_of :name
  
  default_scope order(:name)
  
  attr_reader :repository_theme_tokens
  
  def repository_theme_tokens=(ids)
    self.repository_theme_ids = ids.split(",")
  end
  
  def self.search(search)
    if search
      where('lower(name) LIKE lower(?)', "%#{search}%")
    else
      scoped
    end
  end

end

app/controllers/disciplines_controller.rb
# -*- coding: utf-8 -*-
class DisciplinesController < ApplicationController
  before_filter :check_regular_user
  before_filter :check_admin_user, :except=>['index', 'show']

  def index
    if params[:term]
      @disciplines = Discipline.where("lower(name) LIKE lower(?)","%#{params[:term]}%")
    elsif params[:name]
      @disciplines = Discipline.where("lower(name) LIKE lower(?)","%#{params[:name]}%")
    elsif params[:repository_theme_id]
      @disciplines = Discipline.includes(:repository_themes, :blocks => :examines).search(params[:search]).where(:repository_themes => {:id => params[:repository_theme_id]})
    else
      @disciplines = Discipline.includes(:repository_themes, :blocks => :examines).search(params[:search])
    end

    respond_to do |format|
      format.html
      format.js
      format.json do
        render :json => @disciplines.map(&:attributes)  if params[:name]
        render :json => @disciplines.map(&:name)  if params[:term]
      end
    end
  end


  def show
    @discipline = Discipline.find(params[:id])
  end


  def new
    @discipline = Discipline.new
  end

  def edit
    @discipline = Discipline.find(params[:id])
  end


  def create
    @discipline = Discipline.new(params[:discipline])

    respond_to do |format|
      if @discipline.save
        format.html { redirect_to disciplines_url, :notice => 'Новая дисциплина создана.' }
      else
        format.html { render :action => "new" }
      end
    end
  end


  def update
    @discipline = Discipline.find(params[:id])

    respond_to do |format|
      if @discipline.update_attributes(params[:discipline])
        format.html { redirect_to disciplines_url, :notice => 'Дисциплина отредактирована.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end


  def destroy
    @discipline = Discipline.find(params[:id])
    @discipline.destroy

    respond_to do |format|
      format.html { redirect_to disciplines_url }
    end
  end
end

app/helpers/disciplines_helper.rb
module DisciplinesHelper
end

app/views/disciplines/_disciplines.html.haml
%table{:class => "table table-striped table-bordered"}
  %thead
    %tr
      %th= t "activerecord.attributes.discipline.name"
      %th= t "activerecord.attributes.discipline.blocks"
      %th= t "activerecord.attributes.discipline.examines"
      - if @current_user && @current_user.admin?
        %th Действия
  %tbody
    - @disciplines.each do |discipline|
      %tr
        %td= link_to discipline.name, blocks_path(:discipline_id => discipline)
        %td
          - discipline.blocks.each_with_index do |block, index|
            - i = block.groups.count
            = "Блок #{index+1}:"
            - block.groups.each do |group|
              = link_to group.name, examines_path(:group_id => group)
              - if i > 1
                = ','
              - i -= 1
            %br
        %td
          - discipline.blocks.each do |block|
            - i = block.examines.size
            - block.examines.each do |examine|
              = link_to examine.name, examine, :rel => 'tooltip', :title => "#{l examine.scheduled_date if examine.scheduled_date}"
              - if i > 1
                = ', '
              - i -= 1
            %br
        
        - if @current_user && @current_user.admin?
          %td.actions
            = link_to "<i class='icon-edit'></i>".html_safe, edit_discipline_path(discipline), :class => 'btn btn-mini', :rel => 'tooltip', :title => 'Редактировать'
            = link_to "<i class='icon-trash icon-white'></i>".html_safe, discipline_path(discipline), :method => :delete, :confirm => "#{t "web-app-theme.confirm"}", :class => 'btn btn-mini btn-danger', 'my-rel' => 'tooltip', :title => 'Удалить'

app/views/disciplines/_form.html.haml
%fieldset
  %legend
    = t "controllers.#{controller_name}.#{action_name}"
    - if @discipline.errors.any?
      .alert.alert-error
        %h6 При сохранении произошли ошибки
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name
  .control-group
    = f.label :repository_theme_tokens, "Темы", :class => 'control-label'
    .controls
      = f.text_field :repository_theme_tokens, "data-pre"=>@discipline.repository_themes.map(&:attributes).to_json
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to "Отмена", disciplines_path, :class => 'btn'

app/views/disciplines/edit.html.haml
= form_for @discipline, :html => { :class => "well form-horizontal", :id => "edit_discipline" } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/disciplines/index.html.haml
%h1 Дисциплины

= form_tag disciplines_path, :class => 'well form-search', :method => 'get', :id => 'disciplines_search' do 
  %fieldset
    = text_field_tag :search, params[:search], :class => 'input-medium search-query'
    = submit_tag 'Поиск', :name => nil, :class => 'btn'

#disciplines= render 'disciplines'

- if @current_user && @current_user.admin?
  = link_to 'Новая дисциплина', new_discipline_path, :class => 'btn btn-primary'

.free-space

app/views/disciplines/index.js.haml
$('#disciplines').html("#{escape_javascript render('disciplines')}");

app/views/disciplines/new.html.haml
= form_for @discipline, :html => { :class => 'well form-horizontal' } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/disciplines/old__disciplines.html.haml
%table{:class => "table table-bordered"}
  %thead
    %tr
      %th= t "activerecord.attributes.block.groups"
      %th= t "activerecord.attributes.block.examines"
      %th= t "activerecord.attributes.block.scripts"
      - if @current_user && @current_user.admin?
        %th.actions Действия
  %tbody
    - @blocks.each do |block|
      %tr
        %td
          = block.groups.map(&:name).join(', ')
          .bottom= link_to "<i class='icon-plus'></i> группу".html_safe, edit_block_path(block), :class => 'btn btn-mini btn-success'
        %td
          %ul{:class => 'sortable', 'data-update-url' => "#{sort_examines_path}"}
            - block.examines.each do |examine|
              %li{:class => 'ui-state-default', :id => "examine_#{examine.id}"}
                %span{:class => 'ui-icon ui-icon-arrowthick-2-n-s'}
                =link_to examine.name, examine
                %span{:class => 'link'}= link_to "<i class='icon-plus'></i> сценарий".html_safe, new_script_path(:examine => examine), :class => 'btn btn-mini'
          %br
          %div{:id => "addTest_#{block.id}", :class => "modal hide fade", :style => 'display: none;'}
            = render 'add_test_modal', :block => block
          = link_to "<i class='icon-plus'></i> тест".html_safe, "#addTest_#{block.id}", 'data-toggle' => 'modal', :class => 'btn btn-mini btn-success'
        %td
          - block.examines.each do |examine|
            - examine.scripts.each do |script|
              = link_to script.name, script
        - if @current_user && @current_user.admin?
          %td.actions
            = link_to "<i class='icon-edit'></i>".html_safe, edit_block_path(block), :class => 'btn btn-mini', 'rel' => 'tooltip', 'title' => 'Редактировать'
            = link_to "<i class='icon-trash icon-white'></i>".html_safe, block_path(block), :method => :delete, :confirm => "#{ t "web-app-theme.confirm" }", :class => 'btn btn-mini btn-danger', 'rel' => 'tooltip', 'title' => 'Удалить'

app/views/disciplines/show.html.haml
%span{:class => "label"}= t("activerecord.attributes.discipline.name", :default => t("activerecord.labels.name", :default => "Название")) + ":"
%p= @discipline.name

.form-actions
  = link_to "Назад", disciplines_path, :class => 'btn'
  - if @current_user && @current_user.admin?
    = link_to "Редактировать", edit_discipline_path(@discipline), :class => 'btn'
    = link_to "Удалить", discipline_path(@discipline), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Вы уверены?")}", :class => 'btn btn-danger'