config/routes.rb
Scenario::Application.routes.draw do

  match 'reports' => 'reports#index', :as => :reports
  match 'reports/show' => 'reports#show', :as => :show_reports

  match 'search' => 'search#index', :as => :search

  root :to => 'disciplines#index'

  resources :examines do
    collection { post :sort }
  end

  resources :blocks do
    member do
      post :add_groups
      post :add_examines
    end
    collection { get :year }
  end

  resources :repository_themes do
    collection {get :discipline_themes}
  end

  resources :scripts do
    resources :script_themes do
      resources :script_sub_themes
    end
  end

  resources :disciplines

  resources :groups

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:search].nil?
      @examines = Examine.all
      @scripts = Script.all
    else
      @examines = Examine.where('LOWER(name) LIKE LOWER(?)', "%#{params[:search]}%")
      @scripts = Script.where('LOWER(name) LIKE LOWER(?)', "%#{params[:search]}%")
    end
    
    respond_to do |format|
      format.html
      format.js
    end
  end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_examines.html.haml
%h2 Список тестов

%table{:class => "table table-striped table-bordered"}
  %thead
    %tr
      %th= t "activerecord.attributes.examine.name"
      %th= t "activerecord.attributes.examine.scripts"
      %th= t "activerecord.attributes.examine.blocks"
      - if @current_user && @current_user.admin?
        %th.actions Действия
  %tbody
    - @examines.each do |examine|
      %tr
        %td= link_to examine.name, examine_path(examine)
        %td= examine.scripts.map(&:name).join(', ')
        %td
          - examine.blocks.each do |block|
            = "Блок #{block.block_num}: "
            = block.groups.map(&:name).join(', ')
            %br
        - if @current_user && @current_user.admin?
          %td
            = link_to "<i class='icon-edit'></i>".html_safe, edit_examine_path(examine), :class => 'btn btn-mini', 'rel' => 'tooltip', 'title' => 'Редактировать'
            = link_to "<i class='icon-trash icon-white'></i>".html_safe, examine_path(examine), :method => :delete, :confirm => "#{ t "web-app-theme.confirm" }", :class => 'btn btn-mini btn-danger', 'rel' => 'tooltip', 'title' => 'Удалить'

app/views/search/_scripts.html.haml
%h2 Список сценариев

%table{:class => "table table-striped table-bordered"}
  %thead
    %tr
      %th= t "activerecord.attributes.script.name"
      %th= t("activerecord.attributes.script.script_themes") + ' (' + t("activerecord.attributes.script.repository_themes") + ')'
      %th= t "activerecord.attributes.script.script_subthemes"
      - if @current_user && @current_user.admin?
        %th.actions Действия
  %tbody
    - @scripts.each do |script|
      %tr
        %td= link_to script.name, script_path(script)
        %td
          - script.script_themes.each do |script_theme|
            = script_theme.name + ' (' +script_theme.repository_theme.name + ')'
            %br
        %td
          - script.script_themes.each do |script_theme|
            - script_theme.script_sub_themes.each do |script_sub_theme|
              = script_sub_theme.name
              %br
        - if @current_user && @current_user.admin?
          %td.actions
            = link_to "<i class='icon-edit'></i>".html_safe, edit_script_path(script), :class => 'btn btn-mini', 'rel' => 'tooltip', 'title' => 'Редактировать'
            = link_to "<i class='icon-trash icon-white'></i>".html_safe, script_path(script), :method => :delete, :confirm => "#{ t "web-app-theme.confirm"}", :class => 'btn btn-mini btn-danger', 'rel' => 'tooltip', 'title' => 'Удалить'

app/views/search/index.html.haml
%h2 Поиск
= form_tag search_path, :class => 'well form-search', :method => 'get', :id => 'search' do 
  %fieldset
    = text_field_tag :search, params[:search], :class => 'input-medium search-query'
    = submit_tag 'Поиск', :name => nil, :class => 'btn'

-#- if @examines
#examines
-#= render 'examines'

-#- if @scripts
#scripts
-#= render 'scripts'

.free-space

app/views/search/index.js.haml
- if @examines.count == 0
  $('#examines').html("");
-else
  $('#examines').html("#{escape_javascript render('examines')}");
- if @scripts.count == 0
  $('#scripts').html("");
-else
  $('#scripts').html("#{escape_javascript render('scripts')}");