config/routes.rb
Scenario::Application.routes.draw do

  match 'reports' => 'reports#index', :as => :reports
  match 'reports/show' => 'reports#show', :as => :show_reports

  match 'search' => 'search#index', :as => :search

  root :to => 'disciplines#index'

  resources :examines do
    collection { post :sort }
  end

  resources :blocks do
    member do
      post :add_groups
      post :add_examines
    end
    collection { get :year }
  end

  resources :repository_themes do
    collection {get :discipline_themes}
  end

  resources :scripts do
    resources :script_themes do
      resources :script_sub_themes
    end
  end

  resources :disciplines

  resources :groups

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

end

app/models/script.rb
class Script < ActiveRecord::Base
  #default_scope order(:name)

  belongs_to :examine
  has_many :script_themes, :dependent => :destroy
  accepts_nested_attributes_for :script_themes, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
  
  validates_presence_of :name, :redirect_page, :time
  validates :questions_to_pass, :presence => true, :if => "themes_to_pass.nil?"
  validates :themes_to_pass, :presence => true, :if => "questions_to_pass.nil?"
end

app/controllers/scripts_controller.rb
# -*- coding: utf-8 -*-
class ScriptsController < ApplicationController
  before_filter :check_regular_user
  before_filter :check_admin_user, :except=>['index', 'show']

  def index
    @scripts = Script.includes(:examine).all
  end

  def show
    @script = Script.includes(:examine).find(params[:id])
  end

  def new
    @script = Script.new
  end

  def edit
    @script = Script.find(params[:id])
  end

  def create
    @script = Script.new(params[:script])
    
    params[:examine].each do |key, value|
      @script.examine_id = key
    end

    respond_to do |format|
      if @script.save
        format.html { redirect_to @script, :notice => 'Новый сценарий создан.' }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @script = Script.find(params[:id])

    respond_to do |format|
      if @script.update_attributes(params[:script])
        format.html { redirect_to @script, :notice => 'Сценарий отредактирован.' }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @script = Script.find(params[:id])
    @script.destroy

    respond_to do |format|
      format.html { redirect_to scripts_url }
    end
  end
end

app/helpers/scripts_helper.rb
module ScriptsHelper
end

app/views/scripts/_form.html.haml
%fieldset
  %legend
    = t "controllers.#{controller_name}.#{action_name}"
    - if @script.errors.any?
      .alert.alert-error
        %h6 При сохранении произошли ошибки
  = hidden_field :examine, params[:examine]
  %table{:id => 'mytable'}
    %tbody
      %tr
        %td.first-row
          .control-group
            = f.label :name, "Название", :class => 'control-label'
            .controls
              = f.number_field :name, :class => 'number_field'
        %td.second-row
          .control-group
            = f.label :redirect_page, "Страница перехода", :class => 'control-label'
            .controls
              = f.text_field :redirect_page, :class => 'text_field'
      %tr
        %td
          .control-group
            = f.label :time, "Время", :class => 'control-label'
            .controls
              %div{:class => 'input-append'}
                = f.number_field :time, :class => 'span2-my'
                %span{:class => 'add-on'}> мин.
        %td
          .control-group
            = f.label :results, "Вывод результатов", :class => 'control-label'
            .controls
              %div{:class => 'btn-group', 'data-toggle' => 'buttons-checkbox'}
                %button{:class => 'btn', :id => 'btn-themes'}Темы
                = hidden_field_tag :results_themes, params[:results_themes], :id => 'results-themes'
                %button{:class => 'btn', :id => 'btn-questions'}Вопросы
                = hidden_field_tag :results_questions, params[:results_questions], :id => 'results-questions'
                %button{:class => 'btn', :id => 'btn-detaled'}Детальный
                = hidden_field_tag :results_detaled, params[:results_detaled], :id => 'results-detaled'
      %tr
        %td
          .control-group
            = f.label :blocked, "Заблокирован?", :class => 'control-label'
            .controls
              = f.check_box :blocked, :class => 'check_box'
        %td
          .control-group
            = f.label :order_themes, "Сортировать темы?", :class => 'control-label'
            .controls
              = f.check_box :order_themes, :class => 'check_box'
      %tr
        %td
          .control-group
            = f.label :questions_to_pass, "Необходимо сдать вопросов", :class => 'control-label'
            .controls
              = f.number_field :questions_to_pass, :class => 'number_field'
        %td
          .control-group
            = f.label :themes_to_pass, "Необходимо сдать тем", :class => 'control-label'
            .controls
              = f.number_field :themes_to_pass, :class => 'number_field'

  = f.fields_for :script_themes do |builder|
    = render "script_theme", :f => builder
  .partial= link_to_add_fields "Добавить тему", f, :script_themes
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to "Отмена", scripts_path, :class => 'btn'

app/views/scripts/_script_theme.html.haml
.button-space
%fieldset.partial
  %legend
    Тема
    = link_to_remove_fields "Удалить", f
  %table
    %tbody
      %tr
        %td.first-row
          .control-group
            = f.label :name, "Название", :class => 'control-label'
            .controls
              = f.text_field :name, :class => 'text_field'
        %td.second-row
          .control-group
            = f.label :repository_theme_name, "Репозиторий тем", :class => 'control-label'
            .controls
              = f.text_field :repository_theme_name, {:class => 'autocomplete-field', :onfocus => 'autocompleteField()'}
      %tr
        %td.first-row
          .control-group
            = f.label :questions_to_pass, "Необходимо сдать вопросов", :class => 'control-label'
            .controls
              = f.number_field :questions_to_pass, :class => 'number_field'
        %td.second-row
          .control-group
            = f.label :subthemes_to_pass, "Необходимо сдать подтем", :class => 'control-label'
            .controls
              = f.number_field :subthemes_to_pass, :class => 'number_field'
      %tr
        %td.first-row
          .control-group
            = f.label :order_subthemes, "Сортировать подтемы", :class => 'control-label'
            .controls
              = f.check_box :order_subthemes, :class => 'check_box'
        %td.second-row

  = f.fields_for :script_sub_themes do |builder|
    = render "script_sub_theme", :f => builder
  %div.partial= link_to_add_fields "Добавить подтему", f, :script_sub_themes

app/views/scripts/edit.html.haml
= form_for @script, :html => { :class => "well form-horizontal", :id => "edit_script" } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/scripts/index.html.haml
%h1 Список сценариев
%table{:class => "table table-striped table-bordered"}
  %thead
    %tr
      %th= t "activerecord.attributes.script.name"
      %th= t "activerecord.attributes.script.script_themes"
      %th= t "activerecord.attributes.script.script_subthemes"
      - if @current_user && @current_user.admin?
        %th.actions Действия
  %tbody
    - @scripts.each do |script|
      %tr
        %td= link_to script.name, script_path(script)
        %td
          - script.script_themes.each do |script_theme|
            = script_theme.name
            %br
        %td
          - script.script_themes.each do |script_theme|
            - script_theme.script_sub_themes.each do |script_sub_theme|
              = script_sub_theme.name
              %br
        - if @current_user && @current_user.admin?
          %td.actions
            = link_to "<i class='icon-edit'></i>".html_safe, edit_script_path(script), :class => 'btn btn-mini', 'rel' => 'tooltip', 'title' => 'Редактировать'
            = link_to "<i class='icon-trash icon-white'></i>".html_safe, script_path(script), :method => :delete, :confirm => "#{ t "web-app-theme.confirm"}", :class => 'btn btn-mini btn-danger', 'rel' => 'tooltip', 'title' => 'Удалить'
- if @current_user && @current_user.admin?
  = link_to "Новый сценарий", new_script_path, :class => 'btn btn-primary'

.free-space

app/views/scripts/new.html.haml
= form_for @script, :html => { :class => 'well form-horizontal' } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/scripts/show.html.haml
%p
  %span{:class => "label"}= t("activerecord.attributes.script.name") + ":"
  %b= @script.name
%p
  %span{:class => "label"}= t("activerecord.attributes.script.redirect_page") + ":"
  %b= @script.redirect_page
%p
  %span{:class => "label"}= t("activerecord.attributes.script.time") + ":"
  %b= @script.time.to_s + " мин."
%p
  %span{:class => "label"}= t("activerecord.attributes.script.blocked") + ":"
  %b= @script.blocked ? "Да" : "Нет"
%p
  %span{:class => "label"}= t("activerecord.attributes.script.order_themes") + ":"
  %b= @script.order_themes ? "Да" : "Нет"
%p
  %span{:class => "label"}= t("activerecord.attributes.script.questions_to_pass") + ":"
  %b= @script.questions_to_pass
%p
  %span{:class => "label"}= t("activerecord.attributes.script.themes_to_pass") + ":"
  %b= @script.themes_to_pass
%p
  %span{:class => "label"}= t("activerecord.attributes.script.results") + ":"
  %b= @script.results
%p
  %span{:class => "label"}= t("activerecord.attributes.script.examine_id") + ":"
  %b= @script.examine.name if @script.examine
%p
  %span{:class => "label"}= t("activerecord.attributes.script.base_script_id", :default => t("activerecord.labels.base_script_id", :default => "Base script")) + ":"
  %b= @script.base_script_id
- unless @script.script_themes.blank?
  %span{:class => "label", :style => 'margin-left: 25px;'} Темы:
  - @script.script_themes.each do |theme|
    %p{:style => 'margin-left: 25px;'}= theme.name
    - unless theme.script_sub_themes.blank?
      %span{:class => "label", :style => 'margin-left: 25px;'} Подтемы:
      - theme.script_sub_themes.each do |sub_theme|
        %p{:style => 'margin-left: 25px;'}= sub_theme.name

.form-actions
  = link_to "Назад", scripts_path, :class => 'btn'
  - if @current_user && @current_user.admin?
    = link_to "Редактировать", edit_script_path(@script), :class => 'btn'
    = link_to "Удалить", script_path(@script), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Вы уверены?")}", :class => 'btn btn-danger'