config/routes.rb
Scenario::Application.routes.draw do

  match 'reports' => 'reports#index', :as => :reports
  match 'reports/show' => 'reports#show', :as => :show_reports

  match 'search' => 'search#index', :as => :search

  root :to => 'disciplines#index'

  resources :examines do
    collection { post :sort }
  end

  resources :blocks do
    member do
      post :add_groups
      post :add_examines
    end
    collection { get :year }
  end

  resources :repository_themes do
    collection {get :discipline_themes}
  end

  resources :scripts do
    resources :script_themes do
      resources :script_sub_themes
    end
  end

  resources :disciplines

  resources :groups

  resources :users

  resource :session, :only => [:new, :create, :destroy]

  match 'login' => 'sessions#new', :as => :login

  match 'logout' => 'sessions#destroy', :as => :logout

end

app/models/examine.rb
# -*- coding: utf-8 -*-
class Examine < ActiveRecord::Base
  default_scope order(:ordinal, :scheduled_date)

  #before_create :assign_ordinal 

  has_and_belongs_to_many :blocks
  
  has_many :scripts, :dependent => :destroy
  accepts_nested_attributes_for :scripts, :reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true

  validates_presence_of :name, :num_try, :period, :test_type
  validates :num_try, :numericality=>{:only_integer=>true},:allow_blank=>false
  validates :period, :numericality=>{:only_integer=>true},:allow_blank=>false
  
  EXAMINE_TYPES = ['для слушателей подготовительного факультета',
                   'для учащихся подшефных школ',
                   'для самостоятельного тестирования студентов',
                   'промежуточные тесты контроля знаний для студентов',
                   'экзаменационные тесты для студентов']

  RESULTS = ['Результат по вопросам', 'Результат по темам', 'Детальный результат']
  
  def to_xml(options={})
    super(:except => [:id, :created_at, :updated_at, :ordinal, :examine_id, :base_script_id, :script_id, :script_theme_id], :include => {:scripts => {:include => {:script_themes => {:include => :script_sub_themes}}}})
  end
  
  private
  
  def assign_ordinal
    num = Examine.maximum('ordinal')
    if num.nil?
      self.ordinal = 1
    else
      self.ordinal = num + 1
    end
  end
end

app/controllers/examines_controller.rb
# -*- coding: utf-8 -*-
class ExaminesController < ApplicationController
  before_filter :check_regular_user
  before_filter :check_admin_user, :except=>['show', 'sort']

  def index
    if params[:repository_theme_id]
      @repository_theme = RepositoryTheme.find(params[:repository_theme_id])
      @examines = Examine.includes(:scripts => [:script_themes => :repository_theme]).where('repository_themes.id = ?', params[:repository_theme_id])
    elsif params[:group_id]
      @group = Group.unscoped.find(params[:group_id])
      @disciplines = Discipline.unscoped.includes(:blocks => :groups).where(:blocks => {:groups => {:id => @group.id}})
    else
      @examines = Examine.all
    end
  end


  def show
    @examine = Examine.find(params[:id])
    
    respond_to do |format|
      format.html
      format.xml {render :xml => @examine}
    end
  end

  def new
    @examine = Examine.new
  end


  def edit
    @examine = Examine.find(params[:id])
  end


  def create
    @examine = Examine.new(params[:examine])
    params[:block] = @examine.block_ids
    block = @examine.blocks.first

      if @examine.save
        redirect_to blocks_url(:discipline_id => block.discipline_id), :notice => 'Новый тест создан.'
      else
        render :action => "new"
      end
  end


  def update
    @examine = Examine.find(params[:id])
    block = @examine.blocks.first

      if @examine.update_attributes(params[:examine])
        redirect_to blocks_url(:discipline_id => block.discipline_id), :notice => 'Тест отредактирован.'
      else
        render :action => "edit"
      end
  end


  def destroy
    @examine = Examine.find(params[:id])
    @examine.destroy

    redirect_to examines_url
  end
  
  
  def sort
    params[:examine].each_with_index do |id, index|
      Examine.update_all(['ordinal=?', index+1], ['id=?', id])
    end
    render :nothing => true
  end
end

app/helpers/examines_helper.rb
module ExaminesHelper
end

app/views/examines/_examines.html.haml
%table{:class => "table table-striped table-bordered"}
  %thead
    %tr
      %th= t "activerecord.attributes.examine.name"
      %th= t "activerecord.attributes.examine.scripts"
      %th= t "activerecord.attributes.examine.blocks"
      - if @current_user && @current_user.admin?
        %th.actions Действия
  %tbody
    - examines.each do |examine|
      %tr
        %td= link_to examine.name, examine_path(examine)
        %td= examine.scripts.map(&:name).join(', ')
        %td
          - examine.blocks.each_with_index do |block, i|
            = "Блок #{i+1}: "
            = block.groups.map(&:name).join(', ')
            %br
        - if @current_user && @current_user.admin?
          %td.actions
            = link_to "<i class='icon-edit'></i>".html_safe, edit_examine_path(examine), :class => 'btn btn-mini', 'rel' => 'tooltip', 'title' => 'Редактировать'
            = link_to "<i class='icon-trash icon-white'></i>".html_safe, examine_path(examine), :method => :delete, :confirm => "#{ t "web-app-theme.confirm" }", :class => 'btn btn-mini btn-danger', 'rel' => 'tooltip', 'title' => 'Удалить'

app/views/examines/_form.html.haml
%fieldset
  %legend
    = t "controllers.#{controller_name}.#{action_name}"
    - if @examine.errors.any?
      .alert.alert-error
        %h6 При сохранении произошли ошибки
  
  = hidden_field_tag 'examine[block_ids][]', params[:block], :id => "examine_block_ids_#{params[:block]}"
  %table
    %tbody
      %tr
        %td.first-row
          .control-group
            = f.label :name, :class => 'control-label'
            .controls
              = f.text_field :name, :class => 'text_field'
        %td.second-row
          .control-group
            = f.label :num_try, :class => 'control-label'
            .controls
              = f.number_field :num_try, :class => 'number_field'
      %tr
        %td
          .control-group
            = f.label :period, :class => 'control-label'
            .controls
              .input-append
                = f.number_field :period, :class => 'span2-my'
                %span{:class => 'add-on'}> мин.
        %td
          .control-group
            = f.label :test_type, :class => 'control-label'
            .controls
              - index = 0
              = f.select :test_type, Examine::EXAMINE_TYPES.map{|type| [type, index += 1]}, :class => 'select'
      %tr
        %td
          .control-group
            = f.label :necessary, :class => 'control-label'
            .controls
              = f.check_box :necessary, :class => 'check_box'
        %td
          .control-group
            = f.label :blocked, :class => 'control-label'
            .controls
              = f.check_box :blocked, :class => 'check_box'
      %tr
        %td
          .control-group
            = f.label :w_key, :class => 'control-label'
            .controls
              = f.check_box :w_key, :class => 'checkbox'
        %td
      %tr
        %td
          .control-group
            = f.label :msiu_access, :class => 'control-label'
            .controls
              = f.check_box :msiu_access, :class => 'checkbox'
        %td
          .control-group
            = f.label :ext_access, :class => 'control-label'
            .controls
              = f.check_box :ext_access, :class => 'checkbox'
      %tr
        %td
          .control-group
            = f.label :scheduled_date, :class => 'control-label'
            .controls
              = f.text_field :scheduled_date, {:id => 'datepicker'}
        %td
          .control-group
            = f.label :scheduled_pair, :class => 'control-label'
            .controls
              = f.number_field :scheduled_pair, :class => 'number_field'

  = f.fields_for :scripts do |builder|
    = render "script", :f => builder

  %div= link_to_add_fields "Добавить сценарий", f, :scripts

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to "Отмена", examines_path, :class => 'btn'

app/views/examines/_script.html.haml
%fieldset.partial
  %legend
    Сценарий
    = link_to_remove_fields "Удалить", f
  %table
    %tbody
      %tr
        %td.first-row
          .control-group
            = f.label :name, "Название", :class => 'control-label'
            .controls
              = f.number_field :name, :class => 'number_field'
        %td.second-row
          .control-group
            = f.label :redirect_page, "Страница перехода", :class => 'control-label'
            .controls
              = f.text_field :redirect_page, :class => 'text_field'
      %tr
        %td
          .control-group
            = f.label :time, "Время", :class => 'control-label'
            .controls
              %div{:class => 'input-append'}
                = f.number_field :time, :class => 'span2-my'
                %span{:class => 'add-on'}> мин.
        %td
          .control-group
            = f.label :results, "Вывод результатов", :class => 'control-label'
            .controls
              %div{:class => 'btn-group', 'data-toggle' => 'buttons-checkbox'}
                %button{:class => 'btn', :id => 'btn-themes'}Темы
                = hidden_field_tag :results_themes, params[:results_themes], :id => 'results-themes'
                %button{:class => 'btn', :id => 'btn-questions'}Вопросы
                = hidden_field_tag :results_questions, params[:results_questions], :id => 'results-questions'
                %button{:class => 'btn', :id => 'btn-detaled'}Детальный
                = hidden_field_tag :results_detaled, params[:results_detaled], :id => 'results-detaled'
      %tr
        %td
          .control-group
            = f.label :blocked, "Заблокирован?", :class => 'control-label'
            .controls
              = f.check_box :blocked, :class => 'check_box'
        %td
          .control-group
            = f.label :order_themes, "Сортировать темы?", :class => 'control-label'
            .controls
              = f.check_box :order_themes, :class => 'check_box'
      %tr
        %td
          .control-group
            = f.label :questions_to_pass, "Необходимо сдать вопросов", :class => 'control-label'
            .controls
              = f.number_field :questions_to_pass, :class => 'number_field'
        %td
          .control-group
            = f.label :themes_to_pass, "Необходимо сдать тем", :class => 'control-label'
            .controls
              = f.number_field :themes_to_pass, :class => 'number_field'
      
  = f.fields_for :script_themes do |builder|
    = render "script_theme", :f => builder
    
  %div= link_to_add_fields "Добавить тему", f, :script_themes

app/views/examines/edit.html.haml
= form_for @examine, :html => { :class => "form-horizontal", :id => "edit_examine" } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/examines/index.html.haml
%h1 Список тестов
- if @group
  по дисциплинам для группы:
  %b= @group.name
- if @repository_theme
  по теме:
  %b= @repository_theme.name
  %br
  %br
- if @disciplines
  #accordion-examine.accordion
    - @disciplines.each_with_index do |discipline, index|
      - if discipline.blocks
        - for block in discipline.blocks
          - if block.examines
            .accordion-group
              %h5.accordion-heading= link_to discipline.name, "#accordion#{index+1}", :class => 'accordion-toggle', 'data-toggle' => 'collapse', 'data-parent' => '#accordion-examine'
              %div{:class => 'accordion-body collapse', :id => "accordion#{index+1}"}
                .accordion-inner
                  = render 'examines', :examines => block.examines

-else
  = render 'examines', :examines => @examines


= link_to "Новый тест", new_examine_path, :class => 'btn btn-primary'

.free-space

app/views/examines/new.html.haml
= form_for @examine, :html => { :class => 'form-horizontal' } do |f|
  = render :partial => "form", :locals => {:f => f}

app/views/examines/show.html.haml
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.name") + ":"
  %b= @examine.name
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.necessary") + ":"
  %b= @examine.necessary ? "Да" : "Нет"
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.blocked") + ":"
  %b= @examine.blocked ? "Да" : "Нет"
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.num_try") + ":"
  %b= @examine.num_try
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.period") + ":"
  %b= @examine.period
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.test_type") + ":"
  %b= @examine.test_type
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.w_key") + ":"
  %b= @examine.w_key ? "Да" : "Нет"
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.ext_access") + ":"
  %b= @examine.ext_access ? "Да" : "Нет"
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.msiu_access") + ":"
  %b= @examine.msiu_access ? "Да" : "Нет"
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.scheduled_date") + ":"
  - if @examine.scheduled_date
    %b= l @examine.scheduled_date, :format => :long
%p
  %span{:class => "label"}= t("activerecord.attributes.examine.scheduled_pair") + ":"
  %b= @examine.scheduled_pair
%p
  %span{:class => "label"} Сценарии:
  - @examine.scripts.each do |script|
    %b= script.name
    %span{:class => "label"} Темы:
    - script.script_themes.each do |script_theme|
      %b= script_theme.name
      %span{:class => "label"} Подтемы:
      %b= script_theme.script_sub_themes.map{|sst| sst.name}
  

.form-actions
  = link_to "Назад", examines_path, :class => 'btn'
  - if @current_user && @current_user.admin?
    = link_to "Редактировать", edit_examine_path(@examine), :class => 'btn'
    = link_to "Удалить", examine_path(@examine), :method => "delete", :confirm => "#{t("web-app-theme.confirm", :default => "Вы уверены?")}", :class => 'btn btn-danger'